cargo-features = ["strip"]

[package]
name = "inexor-rgf-core-plugins"
description = "Inexor - Reactive Graph Flow - Core - Plugins"
version = "0.6.0"
authors = ["Andreas Schaeffer <hanack@nooblounge.net"]
edition = "2021"
license = "MIT"

[dependencies]
actix-http = { version = "3.0.0-beta.19" }
actix-web = { version = "4.0.0-beta.21" }
async-std = { version = "1.10", features = ["attributes"] }
indradb-lib = "3"
query_interface = "0.3"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }

inexor-rgf-core-frp = { git = "https://github.com/aschaeffer/inexor-rgf-core-frp.git" }
inexor-rgf-core-model = { git = "https://github.com/aschaeffer/inexor-rgf-core-model.git" }
inexor-rgf-core-reactive = { git = "https://github.com/aschaeffer/inexor-rgf-core-reactive.git" }

[dev-dependencies]
random-string = "1.0"

[build-dependencies]
rustc_version = "0.4.0"

[lib]
crate-type = ["lib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
# 12MB -> 7.8MB
lto = true
# 7.8MB -> 4.5MB
strip = "symbols"
# 4.5MB -> 3.7MB
# opt-level = "z"
